# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Triggers
trigger:
- master
# Pools
pool:
  vmImage: 'ubuntu-latest'
# Steps
steps:
# Say hello
- script: echo Hello, ICT DevOps!
  displayName: 'Say hello'
# Start the build process
- script: bash build.sh
  displayName: 'Run build script'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'auser@13.82.64.79'
    sourceFolder: 'web/'
    contents: '**'
    targetFolder: '/var/www/html'
    cleanTargetFolder: true
    readyTimeout: '20000'
    overwrite: false
    failOnEmptySource: true